version: 2

sources:
  - name: staging
    database: "{{ env_var('DBT_DATABASE', 'markuszhaoq') }}"
    schema: "{{ env_var('DBT_SCHEMA', 'hw04') }}"
      # loaded_at_field: record_loaded_at
    tables:
      - name: fhv_tripdata_ext
         # freshness:
           # error_after: {count: 6, period: hour}
      - name: green_tripdata
         # freshness:
           # error_after: {count: 6, period: hour}
      - name: yellow_tripdata
         # freshness:
           # error_after: {count: 6, period: hour}
            




